config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks",
                                       :registrations      => "registrations" }
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resources :users do
      resources :sites do
        resources :pages
        resources :comments
        post 'rate'
      end
      resources :pictures, only: [:index, :create, :update, :destroy]
    end

    resources :tags do
      collection do
        get 'current'
      end
    end

    root :to => 'sites#home'

    get '/search', to: "search#search", as: "search"
    post '/users/:user_id/pictures/update', to: 'pictures#update', as: 'update_picture'
  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"),
                 constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: :all
  match '', to: redirect("/#{I18n.default_locale}"), via: :all
end

app/controllers/search_controller.rb
require "cgi"

class SearchController < ApplicationController

  HIGHLIGHTS = {
    "Site" => [:title, :description],
    "Page" => [:title, :text],
    "Comment" => :comment
  }

  def search
    params["classes"] ||= ["Site", "Page", "Comment"]
    set_params
    @search = Sunspot.search @classes do
      fulltext params[:query] do
        highlight *@highlights
      end        
    end
    @markdown = Redcarpet::Markdown.new Redcarpet::Render::HTML.new
    respond_to do |format|
      format.js
      format.html
    end
  end

  def set_params
    @classes = params["classes"].map { |name| Object.const_get name }.compact
    @highlights = params["classes"].map { |name| HIGHLIGHTS[name] }.flatten.uniq
  end
end

app/helpers/search_helper.rb
module SearchHelper

  def highlight(hit, stored)
    if hit.highlight(stored) 
      hit.highlight(stored).format { |word| "<span class='highlight'>#{word}</span>" }.html_safe 
    else
      nil
    end
  end
end

app/views/search/_Comment.html.erb
<div class="result-container" onclick='window.location="<%= user_site_path(Site.find(result.commentable_id).user, :id => result.commentable_id) %>"'>
  <div class="result-header">
    <h3>
      <i class="fa fa-comment-o" aria-hidden="true"></i>
      <%= link_to result.user.username, user_path(result.user) %>
    </h3>
  </div>
  <div class="result-description">
    <h4>
      <%= image_tag(result.user.avatar,
                    :class => "img-responsive img-circle img-thumbnail",
                    :align => "left",
                    :hspace => 20,
                    :vspace => 5) %>

      <%= highlight(hit, :comment) || result.comment %>
    </h4>
  </div>
</div>

app/views/search/_Page.html.erb
<div class="result-container" onclick='window.location="<%= user_site_path(result.site.user, result.site) %>";'>
  <div class="result-header">
    <h3>
      <i class="fa fa-file-text-o" aria-hidden="true"></i>
      <%= link_to (highlight(hit, :title) || result.title), user_site_page_path(result.site.user, result.site, result) %>
    </h3>
  </div>
  <div class="result-description">
    <h4>
      <%= image_tag(result.site.logo,
                    :class => "img-responsive img-rounded img-thumbnail",
                    :align => "left",
                    :hspace => 20,
                    :vspace => 5) %>
      <% if result.components.where(:kind => "text").first %>
        <%= highlight(hit, :text) || result.components.where(:kind => "text").first.content[0..200] %>
      <% end %>
    </h4>
  </div>
</div>

app/views/search/_Site.html.erb
<div class="result-container" onclick='window.location="<%= user_site_path(result.user, result) %>"'>
  <div class="result-header">
    <h3>
      <i class="fa fa-globe" aria-hidden="true"></i>
      <%= link_to (highlight(hit, :title) || result.title), user_site_page_path(result.user, result, result.pages.first) %>
    </h3>
  </div>
  <div class="result-description">
    <h4>
      <%= image_tag(result.logo,
                    :class => "img-responsive img-rounded img-thumbnail",
                    :align => "left",
                    :hspace => 20,
                    :vspace => 5) %>
      <%= highlight(hit, :description) || result.description[0..200] %>
    </h4>
  </div>
</div>

app/views/search/_results.html.erb
<div id="#results-list">
  <% @search.each_hit_with_result do |hit, result| %>
    <%= render partial: result.class.to_s, locals: { hit: hit, result: result } %>
  <% end %>
</div>
<h1 style="text-align:center"><%= t("search.not_found") if @search.results.empty? %></h1>

app/views/search/search.html.erb
<div class="col-md-offset-2 col-md-8">
    <p>
      <h1 id="search-label"><%= t(".title") %></h1>
      <div style="text-align: center">
        <div class="btn-group" data-toggle="buttons">
          <label class="btn btn-default toggle" name="Site">
            <input type="checkbox" autocomplete="off"><%= t(".sites") %>
          </label>
          <label class="btn btn-default toggle" name="Page">
            <input type="checkbox" autocomplete="off"><%= t(".pages") %>
          </label>
          <label class="btn btn-default toggle" name="Comment">
            <input type="checkbox" autocomplete="off"><%= t(".comments") %>
          </label>
        </div>
      </div>
      <br>
      <%= text_field_tag(:query,
                         params[:query],
                         :class => "form-control input-lg",
                         :id => "search-form",
                         :url => search_path,
                         :autocomplete => "off") %>
    </p>
  <div id="results">
    <%= render partial: "results" %>
  </div>
</div>

app/views/search/search.js.erb
$("#results").html("<%= j (render partial: 'results') %>");
$('.pagination a').attr('data-remote', 'true');