config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks",
                                       :registrations      => "registrations" }
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resources :users do
      resources :sites do
        resources :pages
        resources :comments
        post 'rate'
      end
      resources :pictures, only: [:index, :create, :update, :destroy]
    end

    resources :tags do
      collection do
        get 'current'
      end
    end

    root :to => 'sites#home'

    get '/search', to: "search#search", as: "search"
    post '/users/:user_id/pictures/update', to: 'pictures#update', as: 'update_picture'
  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"),
                 constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: :all
  match '', to: redirect("/#{I18n.default_locale}"), via: :all
end

app/models/user.rb
class User < ApplicationRecord
  after_save :add_user_role
  before_save :set_avatar

  validates :username, :email, :password, :password_confirmation, :presence => true
  
  include Badginator::Nominee

  has_many :sites
  has_many :pictures
  has_many :comments

  rolify
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :confirmable,
         :omniauth_providers => [:facebook, :vkontakte, :twitter]

  def self.find_for_oauth(access_token)
    if @user = User.where(:provider => access_token.provider)
               .where(:uid => access_token.uid).first
      @user
    else
      @user = User.create(access_token)
      @user.skip_confirmation!
      @user.save
      @user
    end
  end

  def try_add_comment_achievement
    try_add_achievement(:first_comment)
    try_add_achievement(:ten_comments)
    try_add_achievement(:twenty_comments)
  end

  def try_add_site_achievement
    try_add_achievement(:first_site)
    try_add_achievement(:ten_sites)
  end

  private
  def self.create(access_token)
    @user = User.new(:provider => access_token.provider,
                    :uid => access_token.uid,
                    :username => access_token.info.name,
                    :avatar => access_token.info.image,
                    :email => "#{access_token.uid}@temp.tmp",
                    :password => Devise.friendly_token[0,20])
    @user
  end

  def add_user_role
    if User.count == 1
      self.add_role :admin
    else
      self.add_role :user
    end
  end

  def try_add_achievement(achievement)
    status = try_award_badge(achievement)
    if status.code == Badginator::WON
      p "Achievement added: " + status.awarded_badge.badge.name
    end
  end

  def set_avatar
    self.avatar ||= "https://res.cloudinary.com/alex-pat-test-cloud/image/upload/v1471635483/nsp1ckhnwr0kkigh77gt.png"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @sites = @user.sites.all.page(params[:page]).per_page(4)
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def link_to_user(user, mode = :none)

    font_icon = { "twitter" => :twitter, "facebook" => :facebook, "vkontakte" => :vk, nil => :user }
    modes = {
      :comments => -> { "(#{user.comments.length}) " },
      :sites    => -> { "(#{user.sites.length}) "},
      :badges  => -> { "(#{user.badges.length}) " },
      :none => -> { nil }
    }

    user_mod = modes[mode].call
    icon = font_icon[user.provider]
    link = link_to user.username, user_path(user)

    "#{user_mod}<i class='fa fa-#{icon}' aria-hidden='true'></i> #{link}".html_safe
  end

end

app/views/users/shared/_links.html.erb
<%- if devise_mapping.omniauthable? %>
  <%= t("sessions.networks") %> <br>
  <%= link_to '<i class="fa fa-vk fa-2x" aria-hidden="true"></i>'.html_safe, user_vkontakte_omniauth_authorize_path %>
  <%= link_to '<i class="fa fa-facebook fa-2x" aria-hidden="true"></i>'.html_safe, user_facebook_omniauth_authorize_path %>
  <%= link_to '<i class="fa fa-twitter fa-2x" aria-hidden="true"></i>'.html_safe, user_twitter_omniauth_authorize_path %>
<% end %>
<br/>
<br/>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t("layouts.application.navbar.sign_up"), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t("sessions.forgot"), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t("sessions.confirmation_instructions"), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t("sessions.unlock"), new_unlock_path(resource_name) %><br />
<% end -%>