config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks",
                                       :registrations      => "registrations" }
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resources :users do
      resources :sites do
        resources :pages
        resources :comments
        post 'rate'
      end
      resources :pictures, only: [:index, :create, :update, :destroy]
    end

    resources :tags do
      collection do
        get 'current'
      end
    end

    root :to => 'sites#home'

    get '/search', to: "search#search", as: "search"
    post '/users/:user_id/pictures/update', to: 'pictures#update', as: 'update_picture'
  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"),
                 constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: :all
  match '', to: redirect("/#{I18n.default_locale}"), via: :all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] if params[:locale].present?
  end

  def default_url_options(options = {})
    { locale: I18n.locale }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Ucim", root_path, :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <form class="navbar-form navbar-left" action="<%= search_path %>" accept-charset="UTF-8" method="get">
        <div class="form-group">
          <input class="form-control" placeholder=<%= t("layouts.application.navbar.search") %> name="query" type="text">
        </div>
      </form>
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.username %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to t("layouts.application.navbar.profile"), user_path(current_user) %></li>
              <li><%= link_to t("layouts.application.navbar.edit_profile"), edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to t("layouts.application.navbar.new_site"), new_user_site_path(current_user) %></li>
              <li><%= link_to t("layouts.application.navbar.pictures"), user_pictures_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to t("layouts.application.navbar.log_out"), destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("layouts.application.navbar.log_in"), new_user_session_path %></li>
          <li><%= link_to t("layouts.application.navbar.sign_up"), new_user_registration_path %></li>
        <% end %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= params[:locale] %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to_unless_current "en", locale: "en" do %>
                <a>en</a>
              <% end %>
            </li>
            <li>
              <%= link_to_unless_current "ru", locale: "ru" do %>
                <a>ru</a>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/application/_user_site_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to @site.title, @site.pages.first.url, :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
        <% @site.pages.all.each do |page| %>
          <li><%= link_to page.title, user_site_page_path(@site.user, @site, page) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>