config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks",
                                       :registrations      => "registrations" }
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resources :users do
      resources :sites do
        resources :pages
        resources :comments
        post 'rate'
      end
      resources :pictures, only: [:index, :create, :update, :destroy]
    end

    resources :tags do
      collection do
        get 'current'
      end
    end

    root :to => 'sites#home'

    get '/search', to: "search#search", as: "search"
    post '/users/:user_id/pictures/update', to: 'pictures#update', as: 'update_picture'
  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"),
                 constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: :all
  match '', to: redirect("/#{I18n.default_locale}"), via: :all
end

app/models/site.rb
class Site < ApplicationRecord
  validates :title, :description, :logo, :theme, :presence => true

  resourcify
  belongs_to :user
  has_many :pages, dependent: :destroy

  acts_as_taggable
  acts_as_votable
  acts_as_commentable

  searchable do
    text :title, stored: true
    text :description, stored: true
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_user, except: [:tagged, :home]

  def index
    @sites = @user.sites.all
  end
  
  def new
    @site = Site.new
  end

  def create
    @site = @user.sites.new(site_params)
    Component.transaction do
        @site.save
        @user.try_add_site_achievement
        @page = @site.pages.create
    end
    redirect_to edit_user_site_page_path(@user.id, @site.id, @page)
  end

  def edit
    @site = @user.sites.find(params[:id]) 
  end

  def update
    @site = @user.sites.find(params[:id])
    Component.transaction do
      begin
        @site.update_attributes(site_params)
      rescue
        flash[:notice] = "Updating failed"
      else
        flash[:notice] = "Page updated succesfully"
      end
    end
    redirect_to user_site_path
  end

  def destroy
    @site = @user.sites.find(params[:id])
    @site.destroy
    redirect_to user_sites_path
  end

  def show
    @site = @user.sites.find(params[:id])
  end

  def rate
    @site = @user.sites.find(params[:site_id])
    @site.vote_by :voter => current_user, :vote_weight => params[:stars] unless current_user.voted_for? @site
    respond_to do |format|
      format.json { render json: (@site.weighted_score / @site.get_upvotes.size.to_f).round(1).to_json }
    end
  end

  def home
    @sites = Site.all.to_a
    top_sites
    @users = User.all.to_a
    top_commetators
    top_medalists
    top_creators
  end
  
  private
  def set_user
    @user = User.find(params[:user_id])
  end
  
  def site_params
    params.require(:site).permit(:title, :description, :logo, :theme, { :tag_list => [] } )
  end

  def top_sites
    @best_sites = @sites.find_all { |x| x.get_upvotes.length != 0 }.sort do |a,b|
      b.weighted_score / b.get_upvotes.length.to_f - a.weighted_score / a.get_upvotes.length.to_f
    end
    @best_sites = @best_sites[0,10]
  end

  def top_commetators
    @commentators = @users.find_all { |x| x.comments.length != 0 }
    @commentators = @commentators.sort { |a,b| b.comments.length - a.comments.length }[0,10]
  end

  def top_medalists
    @medalists = @users.find_all { |x| x.badges.length != 0 }
    @medalists = @medalists.sort { |a,b| b.badges.length - a.badges.length }[0,10]
  end

  def top_creators
    @creators = @users.find_all { |x| x.sites.length != 0 }
    @creators = @creators.sort { |a,b| b.sites.length - a.sites.length }[0,10]
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_cards.html.erb
<div class="container" xmlns="http://www.w3.org/1999/html">
  <div class="col-md-8">
    <div class="row stylish-panel">
      <% @sites.each do |site| %>
        <div class="col-md-4 col-sm-4 col-xs-12"
             style='height:320px; cursor:pointer'
             onclick="window.location='<%= user_site_path(site.user, site) %>'">
          <div>
            <div>
              <img src="<%= site.logo %>"
                   style="object-fit: cover; height: 200px; width: 200px;"
                   alt="Image doesn't exist"
                   class="img-responsive img-thumbnail img-circle">
              <h3><%= link_to site.title, user_site_page_path(site.user, site, site.pages.first) %></h3>
              <p><%= site.description[0..20] + "..." %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-4">
    <div style='text-align:center'>
      <h3><%= t("home.top.sites") %></h3>
    </div>
    <ol>
      <% @best_sites.each do |site| %>
        <li>
          <%= link_to "(#{(site.weighted_score / site.get_upvotes.size.to_f).round(1)}) #{site.title}",
          user_site_path(site.user, site) %>
        </li>
      <% end %>
    </ol>
    <div style='text-align:center'>
      <h3><%= t("home.top.creators") %></h3>
    </div>
    <ol>
      <% @creators.each do |user| %>
        <li>
          <%= link_to_user user, :sites %>
        </li>
      <% end %>
    </ol>
    <div style='text-align:center'>
      <h3><%= t("home.top.commentators") %></h3>
    </div>
    <ol>
      <% @commentators.each do |user| %>
        <li>
          <%= link_to_user user, :comments %>
        </li>
      <% end %>
    </ol>
<div style='text-align:center'>
  <h3><%= t("home.top.medalists") %></h3>
</div>
    <ol>
      <% @medalists.each do |user| %>
        <li>
          <%= link_to_user user, :badges %>
        </li>
      <% end %>
    </ol>
    <div id="cloud" url="<%= tags_path %>" style="min-height: 200px;"></div>
  </div>
</div>

app/views/sites/_site.html.erb
<div class="user-page-container">
  <div class="user-page-header">
    <h3 style="display: inline-block;">
      <i class="fa fa-globe" aria-hidden="true"></i>
      <%= link_to site.title, user_site_path(site.user.id, site) %>
    </h3>
    <h4 style="display: inline-block; float: right; padding-top: 5px">
      <%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe,
                  edit_user_site_path(site.user, site) if can? :edit, site %>
      <%= link_to("<span class='glyphicon glyphicon-trash'></span>".html_safe,
                  user_site_path(site.user, site), method: :delete) if can? :destroy, site %>
    </h4>
  </div>
  <div class="user-page-description" onclick="window.location = '<%= user_site_path(site.user, site) %>'">
    <h4>
      <%= image_tag(site.logo,
                    :class => "img-responsive img-rounded img-thumbnail",
                    :align => "left",
                    :hspace => 20,
                    :vspace => 5) %>
      <%= site.description %>
    </h4>
  </div>
</div>

app/views/sites/edit.html.erb
<div class="col-lg-10 col-lg-offset-1">
  <div class="form-group">
    <%= form_for @site, url: {:action => :update} do |f| %>
      <p>
        <%= f.label "Title" %>
        <%= f.text_field :title, class: 'form-control' %>
      </p>

      <p>
        <%= f.label "Description" %>
        <%= f.text_area :description, class: 'form-control' %>
      </p>

      <p>
        <%= f.label "Tags" %>
        <div id="magicsuggest" url="<%= current_tags_path %>" site_id="<%= @site.id %>"></div>
      </p>

      <div id="avatar">
        <%= f.label "Logo image" %>
        <div id="picture" class="text-center">
          <% unless @site.logo.nil? %>
              <img src="<%= @site.logo %>"
                   class="logo img-responsive img-rectangle img-thumbnail">
          <% end %>
        </div>
        <br />
        <div class="btn-group">
          <a id="upload" class="btn btn-default">Upload new</a>
          <a data-toggle="modal" data-target="#existModal" class="btn btn-default">Choose from existing</a>
        </div>
      </div>

      <%= f.hidden_field :logo, class: "hidden-input"  %>

      <br />
      <p>
        <%= f.label "Theme" %>
        <%= f.select :theme, %w(readable
              cerulean
              cosmo
              cyborg
              flatly
              journal
              lumen
              paper
              simplex
              slate
              spacelab
              united), {}, { class: "form-control" } %>
      </p>

      <div class="btn-group" role="group">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>
<div class="col-lg-10 col-lg-offset-1">
  <h3>Style example</h3>
  <div id="example">
    <iframe src="/style-example.html" width="100%" height="250px" name="preview" frameborder="0" scrolling="no"></iframe>
  </div>
</div>

<div class="modal fade" id="existModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Your pictures</h4>
      </div>
      <div class="modal-body">
        <% @user.pictures.all.each do |picture| %>
            <a onclick="setImage($existBtn, '<%= picture["public_id"] %>',
                'http://res.cloudinary.com/task4testcloud/image/upload/<%= picture["public_id"] %>'); $('#existModal').modal('hide');">
              <%= cl_image_tag(picture["public_id"], :height => 150, :style => 'padding: 10px; border-radius: 20px;') %></a>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/sites/home.html.erb
<div class="container">
  <div class="container">
    <div class="col-md-12">
      <div class="page-header">
        <h1 class="text-center"><%= t("home.title") %></h1>
      </div>
      <p class="lead text-center"><%= t("home.description") %></p>
    </div>
  </div>
  <%= render partial: "sites/cards" %>
</div>

app/views/sites/index.html.erb
<ul>
  <% @sites.each do |site| %>
    <li>
      <%= link_to site.title, user_site_path(@user, site) %>
      <%= link_to("Delete", user_site_path(@user, site), method: :delete) if can? :edit, site %>
    </li>
  <% end %>
</ul>

app/views/sites/new.html.erb
<div class="col-lg-10 col-lg-offset-1">
  <div class="form-group">
    <%= form_for @site, url: {:action => :create} do |f| %>
      <p>
        <%= f.label "Title" %>
        <%= f.text_field :title, class: 'form-control' %>
      </p>

      <p>
        <%= f.label "Description" %>
        <%= f.text_area :description, class: 'form-control' %>
      </p>

      <p>
        <%= f.label "Tags" %>
        <div id="magicsuggest" url="<%= current_tags_path %>"></div>
      </p>

      <div id="avatar">
        <%= f.label "Logo image" %>
        <div id="picture" class="text-center">
          <% unless @site.logo.nil? %>
              <img src="<%= @site.logo %>"
                   class="logo img-responsive img-rectangle img-thumbnail">
          <% end %>
        </div>
        <br />
        <div class="btn-group">
          <a id="upload" class="btn btn-default">Upload new</a>
          <a data-toggle="modal" data-target="#existModal" class="btn btn-default">Choose from existing</a>
        </div>
      </div>

      <%= f.hidden_field :logo, class: "hidden-input"  %>

      <br />
      <p>
        <%= f.label "Theme" %>
        <%= f.select :theme, %w(readable
              cerulean
              cosmo
              cyborg
              flatly
              journal
              lumen
              paper
              simplex
              slate
              spacelab
              united), {}, { class: "form-control" } %>
      </p>

      <div class="btn-group" role="group">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>
<div class="col-lg-10 col-lg-offset-1">
  <h3>Style example</h3>
  <div id="example">
    <iframe src="/style-example.html" width="100%" height="250px" name="preview" frameborder="0" scrolling="no"></iframe>
  </div>
</div>

<div class="modal fade" id="existModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Your pictures</h4>
      </div>
      <div class="modal-body">
        <% @user.pictures.all.each do |picture| %>
            <a onclick="setImage($existBtn, '<%= picture["public_id"] %>',
                'http://res.cloudinary.com/task4testcloud/image/upload/<%= picture["public_id"] %>'); $('#existModal').modal('hide');">
              <%= cl_image_tag(picture["public_id"], :height => 150, :style => 'padding: 10px; border-radius: 20px;') %></a>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/sites/show.html.erb
<div class="col-md-offset-2 col-md-10">
  <h2 id="site-title"><%= link_to @site.title, user_site_page_path(@site.user, @site, @site.pages.first) %>
    <% if can? :edit, @site %>
      <a href="<%= edit_user_site_path %>"><span class='glyphicon glyphicon-pencil'></span></a>
    <% end %>
    <br />
    <small>
      <%= t("sites.show.by") %>
      <%= link_to_user @user %>
    </small>
  </h2>
  <% unless @site.logo.nil? %>
    <div>
      <img src="<%= @site.logo %>" style='max-height: 200px;' class="img-responsive img-rectangle img-thumbnail">
    </div>
  <% end %>
  <h4>
    <%= @site.description %>
  </h4>
  <p>
    <% if can? :edit, @site %>
      <%= link_to t("sites.show.pages"), user_site_pages_path(:site_id => @site.id) %>
    <% end %>
  </p>
  <h6>
    <%= @site.tag_list.map { |tag| link_to tag, tag_path(:tag_name => tag), :class => "tag" }.join(' ').html_safe %>
  </h6>
  <% if current_user %>
    <input id="star-input"
           name="stars"
           displayonly="<%= current_user.voted_for? @site %>"
           value=<%= if current_user.voted_for?(@site)
                       @site.get_upvotes.find_by(:voter_id => current_user.id).vote_weight
                     else
                       0
                     end %>
           user="<%= current_user.id %>"
           class="rating-loading"
           url="<%= user_site_rate_path(@user, @site) %>">
  <% end %>
  <h4 id="rating"><%= t("sites.show.rating") + (@site.weighted_score / @site.get_upvotes.size.to_f).round(1).to_s  unless @site.get_upvotes.empty? %></h4>

  <br/>
  <div class="row">
    <div class="col-lg-8 col-sm-8 col-xs-12">
      <% if can? :create, @site.comments.new %>
        <%= render "comments/new_comment_field" %>
      <% end %>
      <ul class="media-list comments">
        <%= render @site.comments.all %>
      </ul>
    </div>
  </div>
</div>